//! Build script for openlogi-desktop.
//!
//! Besides the existing update-manifest env hook, this embeds the upstream
//! gpui-component themes *without* vendoring copies into this repo. Those theme
//! files live only in the gpui-component git checkout (the compiled crate
//! doesn't ship them), so we ask `cargo metadata` where gpui-component's source
//! actually resides — which is correct across the local git cache, CI, and
//! Nix's vendored `source-git` tree alike — and copy every theme file it holds
//! into `OUT_DIR`, emitting an include list that `theme.rs` pulls in.
//!
//! `OPENLOGI_THEMES_DIR` overrides the lookup with an explicit path to the
//! gpui-component `themes/` directory, as an escape hatch.
//!
//! It also turns the vendored Piper device drawings into an embedded geometry
//! table — see [`generate_device_art_registry`].
//!
//! Every build-dependency here is one the lockfile already resolves: a crate
//! the resolver hasn't seen would re-resolve the lockfile and bump the
//! precisely-pinned (Cargo.lock-only) gpui rev. So the `cargo metadata` JSON is
//! scanned for `manifest_path` values directly rather than parsed with serde,
//! and `embed-resource` (for [`embed_windows_resources`]), `usvg` and
//! `roxmltree` (for the device art) are all held at versions gpui's own graph
//! already pulls in — each adds an edge, not a crate.

#![expect(
    clippy::expect_used,
    reason = "a build script fails by panicking, so expect — whose message surfaces in the build log — is the idiomatic error path"
)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

fn main() {
    println!("cargo:rerun-if-env-changed=OPENLOGI_UPDATE_MANIFEST_URL");
    println!("cargo:rerun-if-env-changed=OPENLOGI_THEMES_DIR");

    embed_windows_resources();

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let src_dir = locate_themes_dir();
    let dest = out.join("themes");
    fs::create_dir_all(&dest).expect("create OUT_DIR/themes");

    let mut generated = String::from(
        "// @generated by build.rs — upstream gpui-component themes embedded at build time.\n\
         static UPSTREAM_THEME_JSON: &[&str] = &[\n",
    );
    for stem in upstream_theme_stems(&src_dir) {
        let src = src_dir.join(format!("{stem}.json"));
        let json = fs::read_to_string(&src)
            .unwrap_or_else(|e| panic!("cannot read theme `{stem}` at {}: {e}", src.display()));
        fs::write(dest.join(format!("{stem}.json")), json).expect("write theme into OUT_DIR");
        writeln!(
            generated,
            "    include_str!(concat!(env!(\"OUT_DIR\"), \"/themes/{stem}.json\")),"
        )
        .expect("writing to a String cannot fail");
        println!("cargo:rerun-if-changed={}", src.display());
    }
    generated.push_str("];\n");
    fs::write(out.join("builtin_themes.rs"), generated).expect("write builtin_themes.rs");
    generate_device_art_registry(&out);
}

/// Generate the embedded device-art registry from the vendored Piper SVGs.
///
/// Everything the GUI needs about a device drawing is settled here, at build
/// time: which USB ids select which drawing, the device-only SVG the renderer
/// draws, and where every `buttonN` / `ledN` sits inside it. The runtime never
/// parses SVG to find a button, and a drawing that stops matching the format
/// contract fails the build instead of the user's screen.
///
/// Each vendored file carries three Inkscape layers — `Device`, `Buttons`,
/// `LEDs` — where the latter two are callout leaders drawn for Piper's own
/// layout. This app draws its own leader lines, so only the `Device` layer is
/// kept and the canvas is cropped to it; that also removes the wide empty
/// gutter the leaders live in, which would otherwise shrink the device to half
/// the panel.
fn generate_device_art_registry(out: &Path) {
    let svg_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .join("../../design/devices/svg");
    println!("cargo:rerun-if-changed={}", svg_dir.display());

    let mut sources: Vec<PathBuf> = fs::read_dir(&svg_dir)
        .unwrap_or_else(|e| panic!("cannot read device art at {}: {e}", svg_dir.display()))
        .map(|entry| entry.expect("read a device art entry").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "svg"))
        .collect();
    sources.sort();
    assert!(
        sources
            .iter()
            .any(|path| path.file_name() == Some("fallback.svg".as_ref())),
        "design/devices/svg must ship fallback.svg — it is what an unlisted device is drawn as"
    );

    let dest = out.join("device-art");
    fs::create_dir_all(&dest).expect("create OUT_DIR/device-art");

    let mut arts: Vec<DeviceArt> = Vec::with_capacity(sources.len());
    for path in &sources {
        let stem = path
            .file_stem()
            .expect("an `.svg` path has a file stem")
            .to_string_lossy()
            .into_owned();
        let source = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        arts.push(extract_device_art(&stem, &source));
    }
    for art in &arts {
        fs::write(dest.join(format!("{}.svg", art.stem)), &art.device_only)
            .expect("write device-only art into OUT_DIR");
    }

    let lookup_path = svg_dir.join("svg-lookup.ini");
    println!("cargo:rerun-if-changed={}", lookup_path.display());
    let lookup_source = fs::read_to_string(&lookup_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", lookup_path.display()));
    let lookup = parse_svg_lookup(&lookup_source);

    let index_of = |stem: &str| {
        arts.iter()
            .position(|art| art.stem == stem)
            .unwrap_or_else(|| {
                panic!("svg-lookup.ini names {stem}.svg, which is not in design/devices/svg")
            })
    };

    let mut generated = String::from(
        "// @generated by build.rs from design/devices/svg — do not edit.\n\
         /// Every device drawing, cropped to its `Device` layer and embedded.\n\
         static DEVICE_ART: &[DeviceArt] = &[\n",
    );
    for art in &arts {
        writeln!(
            generated,
            "    DeviceArt {{\n        \
                 resource: \"{resource}{stem}.svg\",\n        \
                 canvas: ArtSize {{ width: {width:.1}, height: {height:.1} }},\n        \
                 buttons: &[{buttons}],\n        \
                 leds: &[{leds}],\n    }},",
            resource = DEVICE_ART_RESOURCE_PREFIX,
            stem = art.stem,
            width = art.width,
            height = art.height,
            buttons = render_anchors(&art.buttons),
            leds = render_anchors(&art.leds),
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n\n/// The embedded bytes of every drawing above, keyed by resource path.\nstatic DEVICE_ART_BYTES: &[(&str, &[u8])] = &[\n");
    for art in &arts {
        writeln!(
            generated,
            "    (\"{DEVICE_ART_RESOURCE_PREFIX}{stem}.svg\", include_bytes!(concat!(env!(\"OUT_DIR\"), \"/device-art/{stem}.svg\"))),",
            stem = art.stem,
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n\n/// `svg-lookup.ini`, resolved to indices into [`DEVICE_ART`].\nstatic DEVICE_ART_MATCHES: &[DeviceArtMatch] = &[\n");
    for entry in &lookup {
        let ids = entry
            .ids
            .iter()
            .map(|(vendor, product)| format!("({vendor:#06x}, {product:#06x})"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            generated,
            "    DeviceArtMatch {{ name: \"{name}\", usb_ids: &[{ids}], art: {art} }},",
            name = entry.name,
            art = index_of(&entry.stem),
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n\n");
    writeln!(
        generated,
        "/// Piper's placeholder drawing, served for a device with no entry.\n\
         const FALLBACK_ART: usize = {};",
        index_of("fallback")
    )
    .expect("writing to a String cannot fail");
    fs::write(out.join("builtin_device_art.rs"), generated).expect("write builtin_device_art.rs");
}

/// Resource prefix the GPUI asset source answers device drawings on.
/// Mirrored by `services::device_art`.
const DEVICE_ART_RESOURCE_PREFIX: &str = "device-art/";

/// How much blank space to leave around the device when cropping, in SVG user
/// units. Enough that a thick outline stroke is never clipped by rounding.
const DEVICE_ART_MARGIN: f32 = 4.0;

/// Longer side, in pixels, that every cropped drawing declares.
///
/// The declared size is the only thing GPUI's SVG path has to go on: it
/// rasterises at twice it, once, and scales the texture from there. Left at the
/// file's own user units that is a lottery — these drawings are authored
/// anywhere from 77 to 470 units across — and the small ones would arrive at
/// the panel visibly soft. 600 px is a little above the tallest the mouse model
/// ever draws, so the 1200 px raster still has a device pixel per pixel on a 2×
/// display.
const DEVICE_ART_RENDER_MAX: f32 = 600.0;

/// One `buttonN` or `ledN` element, in the cropped drawing's coordinates.
struct ArtAnchor {
    index: u32,
    x: f32,
    y: f32,
    width: f32,
    height: f32,
}

/// One device drawing, ready to be written into the generated table.
struct DeviceArt {
    stem: String,
    device_only: String,
    width: f32,
    height: f32,
    buttons: Vec<ArtAnchor>,
    leds: Vec<ArtAnchor>,
}

/// One `svg-lookup.ini` section.
struct ArtLookup {
    name: String,
    ids: Vec<(u16, u16)>,
    stem: String,
}

/// Format a set of anchors as Rust struct literals.
///
/// One decimal place, deliberately. It is finer than the rendered pixel these
/// coordinates end up in — and more precision than a stroke bounding box
/// flattened from Bézier curves honestly carries — while keeping every emitted
/// literal short enough that Clippy's `approx_constant` cannot mistake a
/// measurement for π or τ. A generated table has no way to suppress that lint
/// without suppressing it for real code too.
fn render_anchors(anchors: &[ArtAnchor]) -> String {
    anchors
        .iter()
        .map(|anchor| {
            format!(
                "ArtAnchor {{ index: {index}, x: {x:.1}, y: {y:.1}, width: {width:.1}, height: {height:.1} }}",
                index = anchor.index,
                x = anchor.x,
                y = anchor.y,
                width = anchor.width,
                height = anchor.height,
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Crop one vendored drawing to its device and read every anchor out of it.
///
/// The drawing is recomposed twice from the same body: once on its own
/// `viewBox`, to measure the device in the file's user units, and once on a
/// `viewBox` cropped to that measurement. Every anchor is then measured on the
/// cropped document, so the coordinates handed to the GUI are by construction
/// the ones the renderer will draw into — a drawing whose declared size scales
/// its `viewBox` (many of these do, by 3.78×) cannot put the geometry and the
/// image in different coordinate systems.
fn extract_device_art(stem: &str, source: &str) -> DeviceArt {
    let options = usvg::Options::default();
    let body = read_device_body(stem, source);

    // Measured on a 1:1 document, so the bounds come back in the file's own
    // user units — the space a `viewBox` is written in.
    let (view_x, view_y, view_width, view_height) = body.view_box;
    let unscaled = compose_svg(&body, view_x, view_y, view_width, view_height, 1.0);
    let bounds = device_bounds(stem, &unscaled, &options);
    let (crop_x, crop_y) = (
        bounds.x() - DEVICE_ART_MARGIN,
        bounds.y() - DEVICE_ART_MARGIN,
    );
    let (crop_width, crop_height) = (
        bounds.width() + 2.0 * DEVICE_ART_MARGIN,
        bounds.height() + 2.0 * DEVICE_ART_MARGIN,
    );
    let device_only = compose_svg(
        &body,
        crop_x,
        crop_y,
        crop_width,
        crop_height,
        DEVICE_ART_RENDER_MAX / crop_width.max(crop_height),
    );

    let cropped = usvg::Tree::from_str(&device_only, &options)
        .unwrap_or_else(|e| panic!("cropping {stem}.svg produced an unparsable SVG: {e}"));
    let Some(usvg::Node::Group(device)) = cropped.node_by_id("Device") else {
        panic!("cropping {stem}.svg dropped its `Device` layer");
    };
    let mut anchors = Vec::new();
    collect_anchors(device, &mut anchors);
    let buttons = take_anchors(stem, &anchors, "button");
    let leds = take_anchors(stem, &anchors, "led");

    DeviceArt {
        stem: stem.to_owned(),
        device_only,
        width: cropped.size().width(),
        height: cropped.size().height(),
        buttons,
        leds,
    }
}

/// The bounding box of a composed drawing's `Device` layer.
fn device_bounds(stem: &str, composed: &str, options: &usvg::Options) -> usvg::Rect {
    let tree = usvg::Tree::from_str(composed, options)
        .unwrap_or_else(|e| panic!("{stem}.svg is not a parsable SVG: {e}"));
    let Some(usvg::Node::Group(device)) = tree.node_by_id("Device") else {
        panic!("{stem}.svg has no `Device` layer — see design/devices/svg/SVG-FORMAT.md");
    };
    device.abs_stroke_bounding_box()
}

/// Collect every identified shape in a layer, with its absolute bounds.
fn collect_anchors(group: &usvg::Group, out: &mut Vec<(String, usvg::Rect)>) {
    for node in group.children() {
        match node {
            usvg::Node::Group(child) => {
                out.push((child.id().to_owned(), child.abs_stroke_bounding_box()));
                collect_anchors(child, out);
            }
            usvg::Node::Path(path) => {
                out.push((path.id().to_owned(), path.abs_stroke_bounding_box()));
            }
            usvg::Node::Image(image) => {
                out.push((image.id().to_owned(), image.abs_bounding_box()));
            }
            usvg::Node::Text(_) => {}
        }
    }
}

/// Pull every `{prefix}N` anchor out of a collected layer, in index order.
fn take_anchors(stem: &str, anchors: &[(String, usvg::Rect)], prefix: &str) -> Vec<ArtAnchor> {
    let mut found: Vec<ArtAnchor> = Vec::new();
    for (id, bounds) in anchors {
        let Some(index) = id
            .strip_prefix(prefix)
            .and_then(|rest| rest.parse::<u32>().ok())
        else {
            continue;
        };
        assert!(
            !found.iter().any(|anchor| anchor.index == index),
            "{stem}.svg declares `{prefix}{index}` twice"
        );
        found.push(ArtAnchor {
            index,
            x: bounds.x(),
            y: bounds.y(),
            width: bounds.width(),
            height: bounds.height(),
        });
    }
    found.sort_by_key(|anchor| anchor.index);
    found
}

/// One drawing reduced to what a cropped document needs: its namespace
/// declarations, its original `viewBox`, and the markup of its `Device` layer.
struct SvgBody {
    /// `(prefix, uri)` declarations from the root element. The kept markup uses
    /// `inkscape:` and `sodipodi:` attributes, so dropping these would produce
    /// a document no XML parser accepts.
    namespaces: Vec<(Option<String>, String)>,
    /// The original `viewBox`, as `(x, y, width, height)`.
    view_box: (f32, f32, f32, f32),
    /// Everything inside the root element except the other top-level layers.
    body: String,
}

/// Strip a drawing down to its `Device` layer.
///
/// Piper's `Buttons` and `LEDs` layers hold callout leaders drawn for its own
/// widget layout; this app draws its own, and the leaders reach across a gutter
/// two thirds as wide as the canvas. They are cut out at the byte ranges the
/// XML parser reports, so nothing else in the file is disturbed.
fn read_device_body(stem: &str, source: &str) -> SvgBody {
    let document = roxmltree::Document::parse(source)
        .unwrap_or_else(|e| panic!("{stem}.svg is not well-formed XML: {e}"));
    let root = document.root_element();
    let range = root.range();
    assert!(
        source[range.clone()].starts_with("<svg"),
        "{stem}.svg does not have a plain `<svg>` root element"
    );
    let body_start = range.start + end_of_start_tag(&source[range.clone()]);
    let body_end = source[..range.end]
        .rfind('<')
        .expect("a `<svg>` element has a closing tag");

    let mut body = String::new();
    let mut cursor = body_start;
    for child in root.children().filter(roxmltree::Node::is_element) {
        if child.tag_name().name() == "g" && child.attribute("id") != Some("Device") {
            let dropped = child.range();
            body.push_str(&source[cursor..dropped.start]);
            cursor = dropped.end;
        }
    }
    body.push_str(&source[cursor..body_end]);

    let namespaces = root
        .namespaces()
        // `xml` is predeclared by every parser; re-emitting it is redundant.
        .filter(|namespace| namespace.name() != Some("xml"))
        .map(|namespace| {
            (
                namespace.name().map(str::to_owned),
                namespace.uri().to_owned(),
            )
        })
        .collect();

    SvgBody {
        namespaces,
        view_box: parse_view_box(stem, &root),
        body,
    }
}

/// Read a root element's `viewBox`.
fn parse_view_box(stem: &str, root: &roxmltree::Node) -> (f32, f32, f32, f32) {
    let attribute = root
        .attribute("viewBox")
        .unwrap_or_else(|| panic!("{stem}.svg has no viewBox"));
    let values: Vec<f32> = attribute
        .split([' ', ',', '\t', '\n'])
        .filter(|token| !token.is_empty())
        .map(|token| {
            token
                .parse::<f32>()
                .unwrap_or_else(|e| panic!("{stem}.svg has a malformed viewBox `{attribute}`: {e}"))
        })
        .collect();
    let [x, y, width, height] = values[..] else {
        panic!("{stem}.svg viewBox `{attribute}` is not four numbers");
    };
    (x, y, width, height)
}

/// Rebuild a document from a stripped body, on the given canvas.
///
/// The `viewBox` is the canvas in the file's own user units; `scale` sets the
/// declared width and height, and so the space anything measured on the result
/// comes back in. The cropped drawing is composed at the scale that normalises
/// it to [`DEVICE_ART_RENDER_MAX`], which is therefore also the space the
/// geometry table is in — the geometry cannot disagree with the image, because
/// both are read off the same document.
fn compose_svg(body: &SvgBody, x: f32, y: f32, width: f32, height: f32, scale: f32) -> String {
    let (pixel_width, pixel_height) = (width * scale, height * scale);
    let mut svg = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg");
    for (prefix, uri) in &body.namespaces {
        match prefix {
            Some(prefix) => write!(svg, " xmlns:{prefix}=\"{uri}\""),
            None => write!(svg, " xmlns=\"{uri}\""),
        }
        .expect("writing to a String cannot fail");
    }
    write!(
        svg,
        " width=\"{pixel_width:.3}\" height=\"{pixel_height:.3}\" viewBox=\"{x:.3} {y:.3} {width:.3} {height:.3}\">"
    )
    .expect("writing to a String cannot fail");
    svg.push_str(&body.body);
    svg.push_str("</svg>\n");
    svg
}

/// Byte offset just past the `>` that closes an element's start tag, ignoring
/// any `>` inside a quoted attribute value.
fn end_of_start_tag(tag: &str) -> usize {
    let mut quote = None;
    for (offset, character) in tag.char_indices() {
        match (quote, character) {
            (None, '"' | '\'') => quote = Some(character),
            (Some(open), _) if open == character => quote = None,
            (None, '>') => return offset + 1,
            _ => {}
        }
    }
    panic!("an element start tag always closes");
}

/// Parse Piper's `svg-lookup.ini`: one section per device, a `DeviceMatch` list
/// of `bus:vendor:product` triples, and the drawing that serves them.
///
/// The bus is deliberately ignored. A HID++ device reports one product id per
/// transport it supports, and the same physical mouse is matched by its wired
/// id over USB and its wireless id through a receiver — both of which the ini
/// lists under `usb:`, while a Bluetooth-capable model adds a `bluetooth:` id
/// for the same drawing.
fn parse_svg_lookup(source: &str) -> Vec<ArtLookup> {
    let mut entries: Vec<ArtLookup> = Vec::new();
    for line in source.lines().map(str::trim) {
        if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
            continue;
        }
        if let Some(name) = line
            .strip_prefix('[')
            .and_then(|rest| rest.strip_suffix(']'))
        {
            entries.push(ArtLookup {
                name: name.to_owned(),
                ids: Vec::new(),
                stem: String::new(),
            });
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let entry = entries
            .last_mut()
            .unwrap_or_else(|| panic!("svg-lookup.ini has `{line}` before any [section]"));
        match key.trim() {
            "DeviceMatch" => {
                for token in value.split(';').map(str::trim).filter(|t| !t.is_empty()) {
                    let mut parts = token.split(':');
                    let (Some(_bus), Some(vendor), Some(product), None) =
                        (parts.next(), parts.next(), parts.next(), parts.next())
                    else {
                        panic!("svg-lookup.ini has a malformed DeviceMatch token `{token}`");
                    };
                    let ids = (
                        u16::from_str_radix(vendor, 16),
                        u16::from_str_radix(product, 16),
                    );
                    let (Ok(vendor), Ok(product)) = ids else {
                        panic!("svg-lookup.ini has a non-hexadecimal id in `{token}`");
                    };
                    entry.ids.push((vendor, product));
                }
            }
            "Svg" => {
                let stem = value
                    .trim()
                    .strip_suffix(".svg")
                    .unwrap_or_else(|| panic!("svg-lookup.ini `Svg={value}` is not an .svg file"));
                entry.stem.clear();
                entry.stem.push_str(stem);
            }
            _ => {}
        }
    }
    for entry in &entries {
        assert!(
            !entry.stem.is_empty(),
            "svg-lookup.ini section [{}] names no Svg",
            entry.name
        );
        assert!(
            !entry.ids.is_empty(),
            "svg-lookup.ini section [{}] matches no device",
            entry.name
        );
    }
    entries
}

/// Embed the Windows exe resources — the app icon and a VERSIONINFO block —
/// so Explorer, the taskbar, and Task Manager stop showing the generic blank
/// binary. The `.rc` is generated here rather than committed so the version
/// block tracks `CARGO_PKG_VERSION` (a literal would go stale the moment
/// release-plz bumps). No-op off Windows targets.
///
/// Kept in sync with the twin in `crates/openlogi-agent/build.rs` — only the
/// description/filename strings differ.
fn embed_windows_resources() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // rc.exe treats `\` in string literals as escapes; forward slashes are
    // accepted by every resource compiler embed-resource can drive.
    let icon = manifest_dir
        .join("../../design/icon/openlogi.ico")
        .display()
        .to_string()
        .replace('\\', "/");
    println!("cargo:rerun-if-changed={icon}");

    let (major, minor, patch) = (
        env::var("CARGO_PKG_VERSION_MAJOR").expect("CARGO_PKG_VERSION_MAJOR"),
        env::var("CARGO_PKG_VERSION_MINOR").expect("CARGO_PKG_VERSION_MINOR"),
        env::var("CARGO_PKG_VERSION_PATCH").expect("CARGO_PKG_VERSION_PATCH"),
    );
    let version = env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION");
    let rc = format!(
        r#"1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {major},{minor},{patch},0
PRODUCTVERSION {major},{minor},{patch},0
FILEOS 0x40004L
FILETYPE 0x1L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "CompanyName", "AprilNEA"
            VALUE "FileDescription", "OpenLogi"
            VALUE "FileVersion", "{version}"
            VALUE "InternalName", "openlogi-desktop"
            VALUE "OriginalFilename", "OpenLogi.exe"
            VALUE "ProductName", "OpenLogi"
            VALUE "ProductVersion", "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#
    );
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let rc_path = out.join("openlogi-desktop.rc");
    fs::write(&rc_path, rc).expect("write generated .rc into OUT_DIR");
    // manifest_optional: a missing resource compiler downgrades to a cargo
    // warning (icon-less but working exe) instead of failing dev builds on
    // machines without the Windows SDK; release builds run on CI runners that
    // always carry rc.exe.
    embed_resource::compile(&rc_path, embed_resource::NONE)
        .manifest_optional()
        .expect("compile Windows resources");
}

/// Every `<stem>.json` in the upstream themes directory, sorted so the embedded
/// order (and therefore the registry's) is stable across machines.
///
/// The set is read rather than listed: upstream both adds themes and retires
/// them, and a hard-coded list turns either into a broken build or a theme
/// silently missing from the picker the next time the pin moves. Our own
/// `themes/openlogi.json` lives in this repo, so nothing is filtered out here.
fn upstream_theme_stems(dir: &Path) -> Vec<String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read the themes dir at {}: {e}", dir.display()));
    let mut stems: Vec<String> = entries
        .map(|entry| entry.expect("read a themes dir entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .map(|path| {
            path.file_stem()
                .expect("a `.json` path has a file stem")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    stems.sort();
    assert!(
        !stems.is_empty(),
        "no theme JSON found in {}; is this the gpui-component `themes/` directory?",
        dir.display()
    );
    stems
}

/// Find the gpui-component `themes/` directory: an explicit override first, else
/// the dependency's real source location as reported by `cargo metadata`.
fn locate_themes_dir() -> PathBuf {
    if let Some(dir) = env::var_os("OPENLOGI_THEMES_DIR") {
        return PathBuf::from(dir);
    }

    let metadata = cargo_metadata();
    // The themes live at the repo root next to (not inside) the gpui-component
    // crate, so walk up from its manifest until a populated `themes/` appears.
    // `gpui-component-assets` shares the same checkout root, so either match
    // converges on the same directory.
    for manifest in manifest_paths(&metadata).filter(|p| p.contains("gpui-component")) {
        for ancestor in Path::new(manifest).ancestors() {
            let themes = ancestor.join("themes");
            if themes.join("catppuccin.json").is_file() {
                return themes;
            }
        }
    }

    panic!(
        "could not locate the gpui-component themes dir via `cargo metadata`; \
         set OPENLOGI_THEMES_DIR to the gpui-component `themes/` directory"
    );
}

/// Run `cargo metadata` (locked, so it never mutates `Cargo.lock`) and return
/// its JSON stdout.
fn cargo_metadata() -> String {
    println!("cargo:rerun-if-changed=../../Cargo.lock");
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .args(["metadata", "--format-version=1", "--locked"])
        .current_dir(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .output()
        .expect("run `cargo metadata`");
    assert!(
        output.status.success(),
        "`cargo metadata` failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("`cargo metadata` produced non-UTF-8 output")
}

/// Yield every `manifest_path` string value in the metadata JSON. Paths on the
/// platforms that build the GUI (macOS/Linux) contain no characters that JSON
/// would escape, so a direct scan is enough and avoids a serde build-dep.
fn manifest_paths(json: &str) -> impl Iterator<Item = &str> {
    const KEY: &str = "\"manifest_path\":\"";
    json.match_indices(KEY).filter_map(|(i, _)| {
        let rest = &json[i + KEY.len()..];
        rest.find('"').map(|end| &rest[..end])
    })
}
